[Interface]
PrivateKey = ${WG_CLIENT_PRIVATE_KEY}
Address = 10.66.0.2/32

[Peer]
PublicKey = ${WG_SERVER_PUBLIC_KEY}
AllowedIPs = 10.66.0.1/32
Endpoint = ${WG_ENDPOINT}:51820
PersistentKeepalive = 25
