services:
  tailscale:
    image: docker.io/tailscale/tailscale:v1.102.4
    profiles: [tailscale]
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: ${TZ:-America/New_York}
      TS_HOSTNAME: ${VPN_HOSTNAME:-preview}
      TS_AUTHKEY: ${TS_AUTHKEY:-}
      TS_AUTH_ONCE: "true"
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "false"
      TS_EXTRA_ARGS: --accept-dns=false
    volumes:
      - /data/tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "3"
